<?php

class Aset_hbm_Correction {
	
	public function aset_hbm_correction() {
		define('ID_HBM_DATA_CORRECTION','ID_HBM_DATA_CORRECTION');
		define('ID_HBM_DATA_NEW','ID_HBM_DATA_NEW');
		define('CORRECTION_TOTAL','CORRECTION_TOTAL');
		define('TRANSACTION_DATE','TRANSACTION_DATE');
		define('CATEGORY_CODE','CATEGORY_CODE');
		define('DEPRECIATION_FACTOR','DEPRECIATION_FACTOR');
		
		define('PIS_DATE','PIS_DATE');
		define('CURRENCY','CURRENCY');
		define('RUPIAH_COST','RUPIAH_COST');
		define('US_DOLLAR_COST','US_DOLLAR_COST');
		define('EXCHANGE_RATE','EXCHANGE_RATE');
		define('USEFUL_LIFE','USEFUL_LIFE');
		
		define('REMANING_GLL','REMANING_GLL');
		define('CORRECTION_TYPE','CORRECTION_TYPE');
		define('NOTES','NOTES');
		define('CREATED_DATE','CREATED_DATE');
		define('MONTHYEAR_CORRECTION','MONTHYEAR_CORRECTION');
		define('MODIFIED_BY','MODIFIED_BY');
		
	}
}