<?php

class MasterOperator {
	
	public function MasterOperator() {
		define('OPERATOR_CODE', 'OPERATOR_CODE');
		define('MITRA_ASET_CODE', 'MITRA_ASET_CODE');
		define('MITRA_JSV_CODE', 'MITRA_JSV_CODE');
		define('OPERATOR_NAME', 'OPERATOR_NAME');
		define('MITRA_TYPE', 'MITRA_TYPE');
		define('REGION_CODE', 'REGION_CODE');
		define('MODEL_PSC', 'MODEL_PSC');
		define('MONTH_CONTRACT', 'MONTH_CONTRACT');
		define('YEAR_CONTRACT', 'YEAR_CONTRACT');
		define('DOCUMENT_CONTRACT', 'DOCUMENT_CONTRACT');
		
		define('CONTRACT_AREA', 'CONTRACT_AREA');
		define('MITRA_RESPONSIBLE_PERSON', 'MITRA_RESPONSIBLE_PERSON');
		define('MITRA_JOB_TITLE', 'MITRA_JOB_TITLE');
		define('WORKING_ADVANCE', 'WORKING_ADVANCE');
		define('FIRM_COMMITMENT', 'FIRM_COMMITMENT');
		define('TOTAL_BARREL_PRODUCTION', 'TOTAL_BARREL_PRODUCTION');
		define('ID_OIL_TYPE', 'ID_OIL_TYPE');
		define('IS_OIL_PRODUCTION', 'IS_OIL_PRODUCTION');
		define('IS_GAS_PRODUCTION', 'IS_GAS_PRODUCTION');
		define('PRODUCTION_STATUS', 'PRODUCTION_STATUS');
		
		define('MONTH_OPR_END', 'MONTH_OPR_END');
		define('YEAR_OPR_END', 'YEAR_OPR_END');
		define('COMMERCIAL_STATUS', 'COMMERCIAL_STATUS');
		define('COMMERCIAL_ENTRY_DATE', 'COMMERCIAL_ENTRY_DATE');
		define('COMMERCIAL_ATTACH_LETTER', 'COMMERCIAL_ATTACH_LETTER');
		define('OIL_MAX_COST_RECOVERY', 'OIL_MAX_COST_RECOVERY');
		define('OIL_EQUITY_SHARE_MITRA', 'OIL_EQUITY_SHARE_MITRA');
		define('OIL_EQUITY_SHARE_PEP', 'OIL_EQUITY_SHARE_PEP');
		define('GAS_MAX_COST_RECOVERY', 'GAS_MAX_COST_RECOVERY');
		define('GAS_EQUITY_SHARE_MITRA', 'GAS_EQUITY_SHARE_MITRA');
		
		define('GAS_EQUITY_SHARE_PEP', 'GAS_EQUITY_SHARE_PEP');
		define('NETT_SPLIT', 'NETT_SPLIT');
		define('TARIF_PAJAK', 'TARIF_PAJAK');
		define('BANK_GUARANTEE', 'BANK_GUARANTEE');
		define('IS_ADDENDUM', 'IS_ADDENDUM');
		define('EQBNS_NILAI', 'EQBNS_NILAI');
		define('EQBNS_SETORMITRA_DATE', 'EQBNS_SETORMITRA_DATE');
		define('EQBNS_TERIMAPEP_DATE', 'EQBNS_TERIMAPEP_DATE');
		define('SGBNS_NILAI', 'SGBNS_NILAI');
		define('SGBNS_SETORMITRA_DATE', 'SGBNS_SETORMITRA_DATE');
		
		define('SGBNS_TERIMAPEP_DATE', 'SGBNS_TERIMAPEP_DATE');
		define('PRBNS_NILAI', 'PRBNS_NILAI');
		define('PRBNS_SETORMITRA_DATE', 'PRBNS_SETORMITRA_DATE');
		define('PRBNS_TERIMAPEP_DATE', 'PRBNS_TERIMAPEP_DATE');
		define('CREATED_DATE', 'CREATED_DATE');
		define('CREATED_BY', 'CREATED_BY');
	}
}